### ISSUE TITLE
UnicodeDecodeError after entering steam-mv

### ISSUE THREAD

**Issue by SmurgBurglar** [tinfoil-hacks/steam-mv#5]
Traceback (most recent call last):
  File "/usr/local/bin/steam-mv", line 266, in <module>
    app_list = get_app_data(libfolders_list)
  File "/usr/local/bin/steam-mv", line 49, in get_app_data
    app_vdf = parse(f)
  File "/usr/lib/python3.7/site-packages/vdf/__init__.py", line 89, in parse
    for idx, line in enumerate(fp):
  File "/usr/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 128: invalid start byte

**Comment by oaksisfolks** [comment]
Do you have python-vdf installed? If you do, then the problem is with one of your Steam manifest files. 

If you confirm that you have python-vdf installed, I can work some logging into the script by the weekend to give us more information.
