### ISSUE TITLE
The libraryfolders.vdf file is in a different place on my system

### ISSUE THREAD

**Issue by mathuin** [tinfoil-hacks/steam-mv#7]
I am on the publicbeta version of Steam, this may or may not be relevant.

I get the following traceback when attempting to run steam-mv:
```
Traceback (most recent call last):
  File "./steam-mv", line 265, in <module>
    libfolders_list = get_lib_data(default_lib)
  File "./steam-mv", line 22, in get_lib_data
    / "libraryfolders.vdf") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jmt/.local/share/Steam/steamapps/libraryfolders.vdf'
```
My file is in `/home/jmt/.steam/steam/steamapps/libraryfolders.vdf`.

**Comment by Findus23** [comment]
In case you don't know yet:
Simply changing the path in the code works:
```diff
diff --git a/steam-mv b/steam-mv
index 2108675..6975319 100755
--- a/steam-mv
+++ b/steam-mv
@@ -8,7 +8,7 @@ from shutil import disk_usage, move, rmtree
 from vdf import parse
 
 # Define default library folder
-default_lib = {'path': Path.home() / ".local" / "share" / "Steam",
+default_lib = {'path': Path.home() / ".steam" / "steam",
                'steamapps': "steamapps"}
```

**Comment by mathuin** [comment]
I did not look too deeply -- I found a workaround and moved on.  I do think having a path of folders which are searched for the target directory is the right decision, but my feelings were insufficiently strong to generate a pull request at th etime.
